export const DEFAULT_QUIZ_BANK = [
  {
    category: 'Rallyo basics',
    difficulty: 'EASY',
    prompt: 'What does the community leaderboard combine?',
    correctAnswer: 'Approved score events',
    options: ['Approved score events', 'Wallet balances', 'Private messages'],
    hints: ['Think about the shared scoring ledger.'],
  },
  {
    category: 'Rallyo basics',
    difficulty: 'EASY',
    prompt: 'Can a player earn points before linking a Nimiq wallet?',
    correctAnswer: 'Yes',
    options: ['Yes', 'No', 'Only in private chat'],
    hints: ['Wallet linking is for wallet-backed rewards.'],
  },
  {
    category: 'Rallyo basics',
    difficulty: 'EASY',
    prompt: 'Which game asks players to rearrange mixed-up letters?',
    correctAnswer: 'Scramble',
    options: ['Scramble', 'Word Seek', 'Social Tasks'],
    hints: ['The name is a useful clue.'],
  },
  {
    category: 'Rallyo basics',
    difficulty: 'EASY',
    prompt: 'What does Word Seek hide from players?',
    correctAnswer: 'A word',
    options: ['A word', 'A wallet key', 'A Telegram admin list'],
    hints: ['Players guess letters and receive feedback.'],
  },
  {
    category: 'Rallyo basics',
    difficulty: 'EASY',
    prompt: 'What is needed before a competitive round can award seasonal points?',
    correctAnswer: 'An active season',
    options: ['An active season', 'A linked wallet', 'A private group'],
    hints: ['Points belong to a community season.'],
  },
  {
    category: 'Rallyo basics',
    difficulty: 'MEDIUM',
    prompt: 'Which property prevents the same Telegram update from being processed twice?',
    correctAnswer: 'Update idempotency',
    options: ['Update idempotency', 'A longer timer', 'A larger reward'],
    hints: ['The same update should have one durable outcome.'],
  },
  {
    category: 'Rallyo basics',
    difficulty: 'MEDIUM',
    prompt: 'What decides which player wins a First Correct round?',
    correctAnswer: 'The first accepted answer',
    options: ['The first accepted answer', 'The longest answer', 'The player with a wallet'],
    hints: ['The database arbitrates the race.'],
  },
  {
    category: 'Rallyo basics',
    difficulty: 'MEDIUM',
    prompt: 'Why does Rallyo store a question usage record?',
    correctAnswer: 'To avoid recent repetition',
    options: ['To avoid recent repetition', 'To hide the answer', 'To link a wallet'],
    hints: ['A community should see variety over time.'],
  },
  {
    category: 'Nimiq',
    difficulty: 'EASY',
    prompt: 'What is a public wallet address mainly used for?',
    correctAnswer: 'Receiving funds',
    options: ['Receiving funds', 'Signing secretly', 'Recovering a seed phrase'],
    hints: ['It is safe to share publicly.'],
  },
  {
    category: 'Nimiq',
    difficulty: 'EASY',
    prompt: 'What should never be sent to Rallyo in a chat?',
    correctAnswer: 'A private key',
    options: ['A private key', 'A public address', 'A transaction hash'],
    hints: ['Keep secrets out of Telegram.'],
  },
  {
    category: 'Nimiq',
    difficulty: 'MEDIUM',
    prompt: 'What does a wallet signature verify in Rallyo linking?',
    correctAnswer: 'Control of the wallet',
    options: ['Control of the wallet', 'A transfer of funds', 'A Telegram admin role'],
    hints: ['Signing proves control without sending a transaction.'],
  },
  {
    category: 'Nimiq',
    difficulty: 'MEDIUM',
    prompt: 'What is a transaction hash?',
    correctAnswer: 'A transaction identifier',
    options: ['A transaction identifier', 'A seed phrase', 'A private key'],
    hints: ['It lets people look up a transaction.'],
  },
  {
    category: 'Communities',
    difficulty: 'EASY',
    prompt: 'Who controls which Rallyo games are enabled in a community?',
    correctAnswer: 'The authorized community operator',
    options: ['The authorized community operator', 'Any visitor', 'The wallet network'],
    hints: ['Capabilities are community-scoped.'],
  },
  {
    category: 'Communities',
    difficulty: 'EASY',
    prompt: 'Where should an admin look to enable a game?',
    correctAnswer: 'Community settings',
    options: ['Community settings', 'The player wallet', 'A private answer'],
    hints: ['Open the group admin controls.'],
  },
  {
    category: 'Communities',
    difficulty: 'MEDIUM',
    prompt: 'Why are score events shared across game families?',
    correctAnswer: 'To keep one seasonal leaderboard',
    options: ['To keep one seasonal leaderboard', 'To hide game statistics', 'To require a wallet'],
    hints: ['Games contribute to the same community competition.'],
  },
  {
    category: 'Communities',
    difficulty: 'HARD',
    prompt: 'What should happen when a new project word is approved during a live round?',
    correctAnswer: 'It becomes eligible for a later round',
    options: [
      'It becomes eligible for a later round',
      'It changes the active answer',
      'It awards points immediately',
    ],
    hints: ['An active round is immutable.'],
  },
  {
    category: 'Gameplay',
    difficulty: 'EASY',
    prompt: 'What does a Scramble hint reveal?',
    correctAnswer: 'Part of the original term',
    options: ['Part of the original term', 'A private key', 'The next season date'],
    hints: ['Hints reveal positions without ending the round.'],
  },
  {
    category: 'Gameplay',
    difficulty: 'MEDIUM',
    prompt: 'What happens when a scored round reaches its answer deadline?',
    correctAnswer: 'Answers stop scoring',
    options: ['Answers stop scoring', 'Points double', 'The answer changes'],
    hints: ['The scheduler closes due rounds safely.'],
  },
  {
    category: 'Gameplay',
    difficulty: 'MEDIUM',
    prompt: 'What is the purpose of a progressive clue?',
    correctAnswer: 'To reveal more information over time',
    options: [
      'To reveal more information over time',
      'To hide the score ledger',
      'To change communities',
    ],
    hints: ['Earlier answers are worth more.'],
  },
  {
    category: 'Gameplay',
    difficulty: 'HARD',
    prompt: 'Why does winner arbitration happen inside a database transaction?',
    correctAnswer: 'To allow exactly one winner under concurrency',
    options: [
      'To allow exactly one winner under concurrency',
      'To make hints longer',
      'To upload images',
    ],
    hints: ['Several answers can arrive nearly together.'],
  },
  {
    category: 'Telegram',
    difficulty: 'EASY',
    prompt: 'What is the main message in a Rallyo round?',
    correctAnswer: 'The round anchor message',
    options: ['The round anchor message', 'A wallet challenge', 'A hidden admin log'],
    hints: ['Hints and outcomes can update the same message.'],
  },
  {
    category: 'Telegram',
    difficulty: 'MEDIUM',
    prompt: 'Why should Telegram callback data stay compact?',
    correctAnswer: 'Telegram limits its byte length',
    options: ['Telegram limits its byte length', 'It changes the answer', 'It awards extra points'],
    hints: ['Inline buttons have a strict platform limit.'],
  },
  {
    category: 'Telegram',
    difficulty: 'MEDIUM',
    prompt: 'Which format makes a Rallyo winner name clickable when supported?',
    correctAnswer: 'A Telegram user mention',
    options: ['A Telegram user mention', 'A raw database id', 'A wallet seed'],
    hints: ['Telegram can link directly to the player.'],
  },
  {
    category: 'Content',
    difficulty: 'EASY',
    prompt: 'When should generated quiz content enter a live round?',
    correctAnswer: 'After validation and approval',
    options: ['After validation and approval', 'Immediately from the model', 'Only after a payout'],
    hints: ['Live games need deterministic prepared content.'],
  },
  {
    category: 'Content',
    difficulty: 'MEDIUM',
    prompt: 'What does an accepted answer alias provide?',
    correctAnswer: 'Another valid spelling or name',
    options: ['Another valid spelling or name', 'A second leaderboard', 'A longer timer'],
    hints: ['Aliases improve fair answer matching.'],
  },
  {
    category: 'Content',
    difficulty: 'HARD',
    prompt: 'What must an image quiz asset have before live use?',
    correctAnswer: 'Prepared media and provenance metadata',
    options: ['Prepared media and provenance metadata', 'A live web search', 'A wallet signature'],
    hints: ['Rallyo does not scrape during an active round.'],
  },
  {
    category: 'Scoring',
    difficulty: 'EASY',
    prompt: 'Which player identity is used for scoring across communities?',
    correctAnswer: 'The Rallyo player identity',
    options: ['The Rallyo player identity', 'A separate wallet per game', 'A Telegram message id'],
    hints: ['One player can join multiple communities.'],
  },
  {
    category: 'Scoring',
    difficulty: 'MEDIUM',
    prompt: 'What does an idempotency key protect against?',
    correctAnswer: 'Duplicate score awards',
    options: ['Duplicate score awards', 'Longer questions', 'Different communities'],
    hints: ['Retrying a committed action should be harmless.'],
  },
  {
    category: 'Scoring',
    difficulty: 'HARD',
    prompt: 'Does game difficulty create a separate primary leaderboard?',
    correctAnswer: 'No, it only changes round rules',
    options: ['No, it only changes round rules', 'Yes, always', 'Only when a wallet is linked'],
    hints: ['The community has one main seasonal competition.'],
  },
  {
    category: 'Scoring',
    difficulty: 'EASY',
    prompt: 'What kind of points can an admin award in this hackathon build?',
    correctAnswer: 'Positive points with a reason',
    options: ['Positive points with a reason', 'Untracked deductions', 'Wallet-only points'],
    hints: ['Manual awards are audited and positive-only.'],
  },
] as const
